In [131]:
import pandas as pd

In [132]:
data = pd.DataFrame({'ID' : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
             'Name' : ['John', 'Jack', 'Mariah', 'Krishna', 'Danny', 'Lisa', 'Andrew', 'Ravi', 'Garima', 'Kavita'],
             'Gender' :['Male', 'Male', 'Female', 'Male', 'Male', 'Female', 'Male', 'Male', 'Female', 'Female'],
              'Profession' : ['Manager', 'Manager', 'Developer', 'Team Lead', 'Team Lead', 'Assistant Manager', 'Assistant Manager', 'Manager', 'Assistant Manager', 'CEO'],
              'Salary' : [100000, 120000, 95000, 99000, 105000, 145000, 155000, 78000, 167000, 195000],
              'Experience' : [10, 13, 6, 8, 10, 13, 19, 15, 20, 24]})

In [133]:
data.shape

(10, 6)

In [134]:
data

   ID     Name  Gender         Profession  Salary  Experience
0   1     John    Male            Manager  100000          10
1   2     Jack    Male            Manager  120000          13
2   3   Mariah  Female          Developer   95000           6
3   4  Krishna    Male          Team Lead   99000           8
4   5    Danny    Male          Team Lead  105000          10
5   6     Lisa  Female  Assistant Manager  145000          13
6   7   Andrew    Male  Assistant Manager  155000          19
7   8     Ravi    Male            Manager   78000          15
8   9   Garima  Female  Assistant Manager  167000          20
9  10   Kavita  Female                CEO  195000          24

In [135]:
data.drop(columns='Name',inplace=True)

In [136]:
data

   ID  Gender         Profession  Salary  Experience
0   1    Male            Manager  100000          10
1   2    Male            Manager  120000          13
2   3  Female          Developer   95000           6
3   4    Male          Team Lead   99000           8
4   5    Male          Team Lead  105000          10
5   6  Female  Assistant Manager  145000          13
6   7    Male  Assistant Manager  155000          19
7   8    Male            Manager   78000          15
8   9  Female  Assistant Manager  167000          20
9  10  Female                CEO  195000          24

In [137]:
from sklearn.preprocessing import OrdinalEncoder,OneHotEncoder,StandardScaler,MinMaxScaler,RobustScaler

In [138]:
ord_enc= OrdinalEncoder(categories=[['Assistant Manager','Manager','Developer','Team Lead','CEO']])

In [139]:
data['Profession']= ord_enc.fit_transform(data[['Profession']])

In [140]:
data

   ID  Gender  Profession  Salary  Experience
0   1    Male         1.0  100000          10
1   2    Male         1.0  120000          13
2   3  Female         2.0   95000           6
3   4    Male         3.0   99000           8
4   5    Male         3.0  105000          10
5   6  Female         0.0  145000          13
6   7    Male         0.0  155000          19
7   8    Male         1.0   78000          15
8   9  Female         0.0  167000          20
9  10  Female         4.0  195000          24

In [122]:
ord_enc.categories_

[array(['Assistant Manager', 'Manager', 'Developer', 'Team Lead', 'CEO'],
       dtype=object)]

In [123]:
one_hot= OneHotEncoder()

In [124]:
df1=pd.DataFrame(one_hot.fit_transform(data[['Gender']]).toarray())
df1

     0    1
0  0.0  1.0
1  0.0  1.0
2  1.0  0.0
3  0.0  1.0
4  0.0  1.0
5  1.0  0.0
6  0.0  1.0
7  0.0  1.0
8  1.0  0.0
9  1.0  0.0

In [125]:
df2=data.join(df1)

In [126]:
df2.drop('Gender',axis=1,inplace=True)

In [127]:
df2.rename(columns={0:'Female',1:'Male'},inplace=True)

In [85]:
std_sca= StandardScaler()

In [91]:
df2[['Salary','Experience']]= std_sca.fit_transform(df2[['Salary','Experience']])

In [92]:
df2

   ID  Profession    Salary  Experience  Female  Male
0   1         1.0 -0.724184   -0.698926     0.0   1.0
1   2         1.0 -0.164969   -0.147142     0.0   1.0
2   3         2.0 -0.863988   -1.434638     1.0   0.0
3   4         3.0 -0.752145   -1.066782     0.0   1.0
4   5         3.0 -0.584381   -0.698926     0.0   1.0
5   6         0.0  0.534051   -0.147142     1.0   0.0
6   7         0.0  0.813659    0.956425     0.0   1.0
7   8         1.0 -1.339322    0.220714     0.0   1.0
8   9         0.0  1.149188    1.140353     1.0   0.0
9  10         4.0  1.932091    1.876065     1.0   0.0

In [109]:
min_max= MinMaxScaler()

In [110]:
df2[['Salary','Experience']]=min_max.fit_transform(df2[['Salary','Experience']])

In [111]:
df2

   ID  Profession    Salary  Experience  Female  Male
0   1         1.0  0.188034    0.222222     0.0   1.0
1   2         1.0  0.358974    0.388889     0.0   1.0
2   3         2.0  0.145299    0.000000     1.0   0.0
3   4         3.0  0.179487    0.111111     0.0   1.0
4   5         3.0  0.230769    0.222222     0.0   1.0
5   6         0.0  0.572650    0.388889     1.0   0.0
6   7         0.0  0.658120    0.722222     0.0   1.0
7   8         1.0  0.000000    0.500000     0.0   1.0
8   9         0.0  0.760684    0.777778     1.0   0.0
9  10         4.0  1.000000    1.000000     1.0   0.0

In [128]:
rob_sca=RobustScaler()

In [129]:
df2[['Salary','Experience']]=rob_sca.fit_transform(df2[['Salary','Experience']])

In [130]:
df2

   ID  Profession    Salary  Experience  Female  Male
0   1         1.0 -0.234742      -0.375     0.0   1.0
1   2         1.0  0.140845       0.000     0.0   1.0
2   3         2.0 -0.328638      -0.875     1.0   0.0
3   4         3.0 -0.253521      -0.625     0.0   1.0
4   5         3.0 -0.140845      -0.375     0.0   1.0
5   6         0.0  0.610329       0.000     1.0   0.0
6   7         0.0  0.798122       0.750     0.0   1.0
7   8         1.0 -0.647887       0.250     0.0   1.0
8   9         0.0  1.023474       0.875     1.0   0.0
9  10         4.0  1.549296       1.375     1.0   0.0

In [141]:
data

   ID  Gender  Profession  Salary  Experience
0   1    Male         1.0  100000          10
1   2    Male         1.0  120000          13
2   3  Female         2.0   95000           6
3   4    Male         3.0   99000           8
4   5    Male         3.0  105000          10
5   6  Female         0.0  145000          13
6   7    Male         0.0  155000          19
7   8    Male         1.0   78000          15
8   9  Female         0.0  167000          20
9  10  Female         4.0  195000          24

In [149]:
pd.get_dummies(data,dtype='float')

   ID  Profession  Salary  Experience  Gender_Female  Gender_Male
0   1         1.0  100000          10            0.0          1.0
1   2         1.0  120000          13            0.0          1.0
2   3         2.0   95000           6            1.0          0.0
3   4         3.0   99000           8            0.0          1.0
4   5         3.0  105000          10            0.0          1.0
5   6         0.0  145000          13            1.0          0.0
6   7         0.0  155000          19            0.0          1.0
7   8         1.0   78000          15            0.0          1.0
8   9         0.0  167000          20            1.0          0.0
9  10         4.0  195000          24            1.0          0.0