In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

### Simple_Linear_Regression

In [5]:
df= pd.read_csv('sl1.csv')

In [6]:
df

   Area   Price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [7]:
target= df[['Price']]
target

    Price
0  550000
1  565000
2  610000
3  680000
4  725000

In [8]:
features= df.drop(columns='Price')
features

   Area
0  2600
1  3000
2  3200
3  3600
4  4000

In [13]:
x_train,x_test,y_train,y_test=train_test_split(features,target,train_size=0.7,random_state=10)

In [17]:
y_test

    Price
2  610000
3  680000

In [18]:
lin_model=LinearRegression()

In [19]:
lin_model.fit(x_train,y_train)

LinearRegression()

In [25]:
y_pred= lin_model.predict(x_train)

In [26]:
y_pred

array([[534294.87179487],
       [718717.94871795],
       [586987.17948718]])

In [27]:
y_train

    Price
0  550000
4  725000
1  565000

In [28]:
from sklearn.metrics import r2_score

In [29]:
## Training_Validation
r2_score(y_train,y_pred)

0.9591026776589222

In [30]:
## Testing_Validation
y_pred1= lin_model.predict(x_test)
y_pred1

array([[613333.33333333],
       [666025.64102564]])

In [31]:
r2_score(y_test,y_pred1)

0.9157576245488329