### Paired_t_test (Dependent_test)

## A study has conducted to determine the effectiveness of a weight base program. The table below shows the before and after weights of 10 subject in the program. A) Is the program effective for reducing weight? B) (use a 5% significant level) construct a 95% confidence interval and determine the margin of error.

In [ ]:
S.	Bef	Aft
1	185	169
2	192	187
3	206	193
4	177	176
5	225	194
6	168	171
7	256	228
8	239	217
9	199	204
10	218	195

In [1]:
## H0-- Program is not effective
## Ha-- Program is effective

In [2]:
Before=[185,192,206,177,225,168,256,239,199,218]
After=[169,187,193,176,194,171,228,217,204,195]

In [2]:
## tstats= mean_diff/(std_diff/sqrt(n))

In [3]:
diff=[]
for i in range(len(After)):
    diff.append(After[i]-Before[i])
diff

[-16, -5, -13, -1, -31, 3, -28, -22, 5, -23]

In [4]:
import numpy as np
import scipy.stats as stats

In [5]:
mean= np.mean(diff)
mean

-13.1

In [8]:
std= np.std(diff,ddof=1)
std

13.02518927139086

In [9]:
tstats= mean/(std/np.sqrt(10))
tstats

-3.180440336417639

In [10]:
stats.ttest_rel(After,Before)

TtestResult(statistic=-3.180440336417639, pvalue=0.011176870661470717, df=9)

In [11]:
t_critical= stats.t.ppf(0.975,9)
t_critical

2.2621571628540993

In [12]:
## pvalue < alpha value and stats value is in the rejection region reject HO
## Program is effective

## ANOVA(F-test)

In [14]:
stats.f.ppf(0.95,2,12)

3.8852938346523946

In [15]:
a=[2,3,7,2,6]
b=[10,8,7,5,10]
c=[10,13,14,13,15]

In [16]:
## Fstats=(Variance_bet_group/df1)/(Variance_within_group/df2)

In [24]:
## Variance_bet_group
## sum(overall_mean-mean_samples)**2
df1=2
df2=4+4+4
df2
n=5

In [21]:
mean_a= np.mean(a)
mean_b= np.mean(b)
mean_c= np.mean(c)
print('mean_a:',mean_a,', mean_b:',mean_b,', mean_c:',mean_c)

mean_a: 4.0 , mean_b: 8.0 , mean_c: 13.0

In [22]:
Overall_mean= (mean_a+mean_b+mean_c)/3
Overall_mean

8.333333333333334

In [25]:
Variance_bet_group= n*((Overall_mean-mean_a)**2)+n*((Overall_mean-mean_b)**2)+n*((Overall_mean-mean_c)**2)
Variance_bet_group

203.33333333333331

In [26]:
var_within_group= sum((a-mean_a)**2)+ sum((b-mean_b)**2)+sum((c-mean_c)**2)
var_within_group

54.0

In [27]:
Fstats= (Variance_bet_group/df1)/(var_within_group/df2)
Fstats

22.59259259259259

In [28]:
stats.f_oneway(a,b,c)

F_onewayResult(statistic=22.59259259259259, pvalue=8.538592454274673e-05)

In [30]:
import pandas as pd
df= pd.read_csv('Plant_growth.csv')

In [31]:
df

    weight treatment_type
0     4.17           ctrl
1     5.58           ctrl
2     5.18           ctrl
3     6.11           ctrl
4     4.50           ctrl
5     4.61           ctrl
6     5.17           ctrl
7     4.53           ctrl
8     5.33           ctrl
9     5.14           ctrl
10    4.81           trt1
11    4.17           trt1
12    4.41           trt1
13    3.59           trt1
14    5.87           trt1
15    3.83           trt1
16    6.03           trt1
17    4.89           trt1
18    4.32           trt1
19    4.69           trt1
20    6.31           trt2
21    5.12           trt2
22    5.54           trt2
23    5.50           trt2
24    5.37           trt2
25    5.29           trt2
26    4.92           trt2
27    6.15           trt2
28    5.80           trt2
29    5.26           trt2

In [32]:
df['treatment_type'].value_counts()

treatment_type
ctrl    10
trt1    10
trt2    10
Name: count, dtype: int64

In [33]:
df.shape

(30, 2)

In [40]:
## H0= ctrl!=trt1!=trt2
## Ha= ctrl==trt1==trt2

In [36]:
ctrl=df[df['treatment_type']=='ctrl']['weight']
ctrl

0    4.17
1    5.58
2    5.18
3    6.11
4    4.50
5    4.61
6    5.17
7    4.53
8    5.33
9    5.14
Name: weight, dtype: float64

In [37]:
trt1=df[df['treatment_type']=='trt1']['weight']
trt1

10    4.81
11    4.17
12    4.41
13    3.59
14    5.87
15    3.83
16    6.03
17    4.89
18    4.32
19    4.69
Name: weight, dtype: float64

In [38]:
trt2=df[df['treatment_type']=='trt2']['weight']
trt2

20    6.31
21    5.12
22    5.54
23    5.50
24    5.37
25    5.29
26    4.92
27    6.15
28    5.80
29    5.26
Name: weight, dtype: float64

In [41]:
import scipy.stats as stats

In [42]:
stats.f_oneway(ctrl,trt1,trt2)

F_onewayResult(statistic=4.846087862380136, pvalue=0.015909958325622895)

In [43]:
stats.f.ppf(0.95,2,27)

3.3541308285291986

In [44]:
## Fcritical<Fstats we reject HO, ctrl==trt1==trt2

## Chisquare_test

In [45]:
Expected= [100,150,250]
Observed=[140,160,200]

In [51]:
chi_stats=stats.chisquare(Observed,Expected)
chi_stats

Power_divergenceResult(statistic=26.666666666666668, pvalue=1.61959679231261e-06)

In [49]:
chi_critical=stats.chi2.ppf(0.95,2)
chi_critical

5.991464547107979

## A school principal would like to know which day of the week students are most likely to be absent. The principal expects that students will be absent equally during the 5-day school weak. The principal selects a random sample of 100 teachers asking them which day of the week they had the highest number of student absences. The observed and expected results are shown in table below. Based on the results do the days for the highest number of absences occur with equal frequencies? (Use 	a 5% significant level)

	        Mo	Tu	We	Thu Fr
observed	23	16	14	19	28
Expected	20	20	20	20	20

In [54]:
## H0--Absentees are not same on weekdays
## Ha-- Absentess are same on weekdays
## alpha=-0.05, CI=0.95
## n=5
## df=n-1=4

In [55]:
chi_critical= stats.chi2.ppf(0.95,4)
chi_critical

9.487729036781154

In [56]:
observed=[23,16,14,19,28]
Expected=[20,20,20,20,20]

In [57]:
stats.chisquare(observed,Expected)

Power_divergenceResult(statistic=6.3, pvalue=0.1778363264982168)

In [59]:
## Chi_critical>Chi_stats--fail to reject H0, Absentees not same on weekdays

In [61]:
import pandas as pd
df= pd.read_csv('Voting_pattern.csv')

In [63]:
df.shape

(1000, 2)

In [64]:
df.columns

Index(['RACE', 'PARTY'], dtype='object')

In [65]:
df.RACE.value_counts()

RACE
WHITE               534
HISPANIC            236
African American    151
ASIAN                42
OTHER                37
Name: count, dtype: int64

In [66]:
df.PARTY.value_counts()

PARTY
PQR    404
ABC    403
XYZ    193
Name: count, dtype: int64

In [67]:
df

         RACE PARTY
0       WHITE   PQR
1       WHITE   PQR
2       WHITE   ABC
3    HISPANIC   ABC
4       ASIAN   ABC
..        ...   ...
995  HISPANIC   PQR
996     WHITE   PQR
997     WHITE   PQR
998  HISPANIC   ABC
999     WHITE   PQR

[1000 rows x 2 columns]

In [75]:
df1=pd.crosstab(index=df.RACE,columns=df.PARTY)
df1

PARTY             ABC  PQR  XYZ
RACE
ASIAN              19   15    8
African American   60   59   32
HISPANIC          105   86   45
OTHER              12   17    8
WHITE             207  227  100

In [76]:
42*403/1000

16.926

In [77]:
236*404/1000

95.344

In [78]:
stats.chi2_contingency(df1)

Chi2ContingencyResult(statistic=4.737839473077469, pvalue=0.7851934085104637, dof=8, expected_freq=array([[ 16.926,  16.968,   8.106],
       [ 60.853,  61.004,  29.143],
       [ 95.108,  95.344,  45.548],
       [ 14.911,  14.948,   7.141],
       [215.202, 215.736, 103.062]]))

In [79]:
stats.chi2.ppf(0.95,8)

15.507313055865453